SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT 
--     ROWID, P.RQ_AA_OVERRIDE, P.EFFDT, P.EFF_STATUS, 
--     P.DESCR, P.DESCRSHORT, P.DESCR254A, 
--     P.INSTITUTION, P.ACAD_CAREER, P.ACAD_PROG, 
--     P.ACAD_PLAN, P.RQ_AA_WHO_CODE, P.RQ_AA_WHO_DATA, 
--     P.RQ_AA_OVRD_OPCODE, P.RQRMNT_GROUP, P.REQUIREMENT, 
--     P.RQ_LINE_NBR, P.RQ_AA_OVRD_CRS_NBR, P.DIRCT_TYPE, 
--     P.RQ_CRSE_SOURCE, P.CRSE_ID, P.CRSE_OFFER_NBR, 
--     P.STRM, P.CLASS_NBR, P.UNITS_DIRECTED, 
--     P.PROCESSED, P.GRADE_POINTS_MIN
--  FROM NS_MIGRA.PS_ETY_EXE_CND_MIG_TMP_V11 P
--
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('01/01/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '292', '544', 'STDN', '1007322782', 'DRCT', '585', '58514', '30', '0', 'S', 'ENRL', '012922', 1, '1730', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('01/01/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '292', '544', 'STDN', '1002799520', 'DRCT', '585', '58514', '30', '0', 'S', 'ENRL', '012922', 1, '1730', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('01/01/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '237', '510', 'STDN', '1002634672', 'DRCT', '586', '58614', '40', '0', 'S', 'ENRL', '012913', 1, '1720', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('01/01/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '237', '510', 'STDN', '1002637351', 'DRCT', '586', '58614', '40', '0', 'S', 'ENRL', '012913', 1, '1720', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('3', TO_DATE('05/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'PREG', '207', '532', 'STDN', '1053776765', 'DRCT', '532', '53210', '10', '1', 'S', 'ENRL', '013664', 1, '1400', 0, 2, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('1', TO_DATE('05/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'PREG', '207', '532', 'STDN', '1053776765', 'DRCT', '532', '53210', '10', '0', 'S', 'ENRL', '013194', 1, '1400', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('2', TO_DATE('05/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'PREG', '207', '532', 'STDN', '1053776765', 'DRCT', '532', '53210', '20', '0', 'S', 'ENRL', '016334', 1, '1580', 0, 2, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('05/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'PREG', '207', '532', 'STDN', '1053776765', 'DRCT', '532', '53214', '50', '0', 'S', 'ENRL', '021125', 1, '1580', 0, 2, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('1', TO_DATE('10/26/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '216', '447', 'STDN', '1054547193', 'DRCT', '447', '44710', '20', '0', 'S', 'ENRL', '016299', 1, '1630', 0, 1, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('10/26/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '216', '447', 'STDN', '1054547193', 'DRCT', '447', '44711', '10', '0', 'S', 'ENRL', '018557', 1, '1660', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('1', TO_DATE('01/01/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'EDUC', '238', '586', 'STDN', '1002543842', 'DRCT', '586', '58614', '40', '0', 'S', 'ENRL', '012913', 1, '1720', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('01/01/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'EDUC', '238', '586', 'STDN', '1002543842', 'DRCT', '586', '58614', '20', '0', 'S', 'ENRL', '012799', 1, '1750', 0, 2, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/21/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1073328292', 'DRCT', '584', '58414', '20', '0', 'S', 'ENRL', '019704', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053807446', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053860350', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/22/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1073328407', 'DRCT', '584', '58414', '20', '0', 'S', 'ENRL', '019704', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('2', TO_DATE('12/17/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053848519', 'DRCT', '584', '58414', '70', '0', 'S', 'ENRL', '019727', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053806191', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/14/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1007802824', 'DRCT', '584', '58414', '20', '0', 'S', 'ENRL', '019704', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/03/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1061048277', 'DRCT', '584', '58414', '20', '0', 'S', 'ENRL', '019704', 1, '1740', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1059785613', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053767159', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('1', TO_DATE('12/17/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1060650364', 'DRCT', '584', '58414', '70', '0', 'S', 'ENRL', '019727', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1007729225', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053872886', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053869928', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('12/17/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053802545', 'DRCT', '584', '58414', '20', '0', 'S', 'ENRL', '019727', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/01/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1053864200', 'DRCT', '584', '58411', '10', '0', 'S', 'ENRL', '018431', 1, '1730', 0, 4, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('04/21/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '1054571026', 'DRCT', '584', '58414', '20', '0', 'S', 'ENRL', '019704', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('12/17/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'TECN', '380', '584', 'STDN', '15962700', 'DRCT', '584', '58414', '70', '0', 'S', 'ENRL', '019727', 1, '1750', 0, 3, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('02/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'EDUC', '384', '585', 'STDN', '1002591745', 'DRCT', '585', '58510', '10', '0', 'S', 'ENRL', '012938', 1, '1750', 0, 2, ' ', '3');
Insert into PS_ETY_EXE_CND_MIG
   (RQ_AA_OVERRIDE, EFFDT, EFF_STATUS, DESCR, DESCRSHORT, DESCR254A, INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, RQ_AA_WHO_CODE, RQ_AA_WHO_DATA, RQ_AA_OVRD_OPCODE, RQRMNT_GROUP, REQUIREMENT, RQ_LINE_NBR, RQ_AA_OVRD_CRS_NBR, DIRCT_TYPE, RQ_CRSE_SOURCE, CRSE_ID, CRSE_OFFER_NBR, STRM, CLASS_NBR, UNITS_DIRECTED, PROCESSED, GRADE_POINTS_MIN)
 Values
   ('0', TO_DATE('02/12/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'A', 'Reconocimiento migrado SIA ant', 'Rec migra', 'Reconocimiento migrado SIA anterior', 'UCALD', 'EDUC', '384', '585', 'STDN', '1002637004', 'DRCT', '585', '58510', '10', '0', 'S', 'ENRL', '012938', 1, '1750', 0, 2, ' ', '3');
COMMIT;
